/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:02dbfc60-db13-4536-8104-c260d69565e3",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_12Z7EsZsH",
    "aws_user_pools_web_client_id": "177m69ral86i5d72oo2lao7iul",
    "oauth": {},
    "aws_user_files_s3_bucket": "s3jamstackecommerce223149-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-2",
    "aws_appsync_graphqlEndpoint": "https://uwtzm4ojwzehxfv6bjatgbw44m.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-j7iuvxwf4rhy5dtvpmowrnixye"
};


export default awsmobile;
